Second order Kalman prediction is updated
wildwolf-team/WolfVision pull request #44
Opened 2021-07-22 02:31 UTC by robomaster-shl

Second order Kalman prediction is updated

2021-07-22 03:45 UTC, fqjun commented on module/filter/basic_kalman.hpp
> +#  define RM_KALMANFILTER_H
这里有两个重复包含保护是什么情况，使用其一即可

2021-07-22 03:45 UTC, fqjun commented on module/filter/basic_kalman.hpp
> +using namespace std;
禁止使用全局命名空间

2021-07-22 03:46 UTC, fqjun commented on module/filter/basic_kalman.hpp
> +using namespace cv;
同上

2021-07-22 03:47 UTC, fqjun commented on module/filter/basic_kalman.hpp
> +
将原有的`abstract_kalman.hpp`包含回来，不要破坏原有结构

2021-07-22 03:50 UTC, fqjun commented on module/filter/basic_kalman.hpp
> +    float merge_run(float data1, float data2) {
只供输入不作修改返回值的变量请用 `const` 和 引用 `&` 修饰，例如：`const float& data1`

2021-07-22 03:51 UTC, fqjun requested changes
1. 编译不通过可能是因为文件包含保护的重复使用导致，请本地自行编译检查
2. 未进行格式化
3. 函数形参请进行输入保护
4. 修改完毕后重新push，pr会自动更新

2021-07-22 08:59 UTC, fqjun commented
头文件引入写在命名空间外！

2021-07-24 04:10 UTC, fqjun commented
改好了请push到仓库pr才能接受到更新

2021-07-24 08:20 UTC, fqjun commented on module/filter/basic_kalman.hpp
> -#include "abstract_kalman.hpp"
还是删掉了呀苏老板

2021-07-24 08:21 UTC, fqjun requested changes
将原来的头文件添加回来

2021-07-24 09:14 UTC, iChizer0 commented on module/filter/basic_kalman.cpp
> +RM_kalmanfilter::RM_kalmanfilter() : KF_(4, 2) {
```suggestion
KalmanFilter::KalmanFilter() : KF_(4, 2) {
```

类命名规范，`KF_()` 继承参数未说明

2021-07-24 09:15 UTC, iChizer0 commented on module/filter/basic_kalman.cpp
> +cv::Point2f RM_kalmanfilter::predict_point(cv::Point2f _p) {
```suggestion
cv::Point2f KalmanFilter::predictPoint(const cv::Point2f& _p) {
```

命名规范，显式地使用引用

2021-07-24 09:16 UTC, iChizer0 commented on module/filter/basic_kalman.cpp
> +float RM_kalmanfilter::use_RM_KF(float top) {
命名规范，显式地使用引用

2021-07-24 09:17 UTC, iChizer0 commented on module/filter/basic_kalman.cpp
> +
使用 `fmt::print();`

2021-07-24 09:29 UTC, iChizer0 commented on module/filter/basic_kalman.cpp
> +  top_angle_differ.get_top_times++;  // 自动计数 . 获得陀螺仪数据的次数
```suggestion
  ++top_angle_differ.get_top_times;  // 自动计数 . 获得陀螺仪数据的次数
```

为了保证风格统一，显式使用前置的 `++`。如果在表达式中，无非必要建议使用前置的 `++` 避免临时值的生成：

```asm
// num++
mov     DWORD PTR [rbp-20], edi
mov     eax, DWORD PTR [rbp-20]
lea     edx, [rax+1]
mov     DWORD PTR [rbp-20], edx
mov     DWORD PTR [rbp-4], eax
mov     eax, DWORD PTR [rbp-20]

// ++num
mov     DWORD PTR [rbp-20], edi
add     DWORD PTR [rbp-20], 1
mov     eax, DWORD PTR [rbp-20]
mov     DWORD PTR [rbp-4], eax
mov     eax, DWORD PTR [rbp-20]
```

2021-07-24 09:34 UTC, iChizer0 commented on module/filter/basic_kalman.hpp
> +        p_ = (1 - kg_) * p_pre_;                      // p(k|k)   = (I-kg(k)H)P(k|k-1)
```suggestion
    float run(float data) {
        x_pre_ = x_;                                      // x(k|k-1) = AX(k-1|k-1)+BU(k)
        p_pre_ = p_ + Q_;                                 // p(k|k-1) = Ap(k-1|k-1)A'+Q
        kg_    = p_pre_ / (p_pre_ + R_);                  // kg(k)    = p(k|k-1)H'/(Hp(k|k-1)'+R)
        x_     = x_pre_ + kg_ * (data - x_pre_);          // x(k|k)   = X(k|k-1)+kg(k)(Z(k)-HX(k|k-1))
        p_     = (1 - kg_) * p_pre_;                      // p(k|k)   = (I-kg(k)H)P(k|k-1)
```

2021-07-24 09:35 UTC, iChizer0 commented on module/filter/basic_kalman.hpp
> +class Kalman1 {
命名规范

2021-07-24 09:36 UTC, iChizer0 commented on module/filter/basic_kalman.hpp
> + public:
```suggestion
 private:
```

是否考虑使用私有声明，若果没有直接的外部使用

2021-07-24 09:49 UTC, iChizer0 commented
@fqjun

2021-07-27 03:55 UTC, fqjun commented on module/filter/basic_kalman.hpp
>          t_ = static_cast<float>(t);
```suggestion
        R_ = static_cast<float>(R)*0.01f;
        Q_ = static_cast<float>(Q)*0.01f;
        t_ = static_cast<float>(t);
```

2021-08-28 14:17 UTC, closed without merging