Add file header comments and code comments and instructions for use d…
wildwolf-team/WolfVision pull request #60
Opened 2021-08-27 17:27 UTC by roboxxltd

…ocuments

**Summary:**

fix: Add file header comments and code comments
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Docs
- [ ] Build-related changes
- [ ] Other, please describe:

**The PR fulfills these requirements:**

- [x] Related documents have been updated
- [ ] Related tests have been updated

2021-08-28 06:18 UTC, roboxxltd commented
Fix style issues of code and comments

2021-08-28 13:00 UTC, fqjun reviewed
检查并删除注释前多余的空格

2021-08-28 13:32 UTC, roboxxltd commented on module/armor/basic_armor.hpp
> +  // 灯条高宽比范围
这个是什么

2021-08-28 13:47 UTC, roboxxltd commented on module/armor/basic_armor.hpp
> +  // 灯条高宽比范围
这个位置前面有空格

2021-08-29 04:55 UTC, fqjun requested changes
1. 主函数的文件注释改为主函数
2. 文件头部的作者注释格式统一为分行

2021-08-29 04:55 UTC, fqjun commented on base/wolfvision.cpp
> + * @author XX (2796393320@qq.com) WCJJJ (1767851382@qq.com)
统一格式为分行

2021-08-29 06:13 UTC, fqjun requested changes
1. 个别位置没对齐
2. 作者的注释需进行格式统一

2021-08-29 06:13 UTC, fqjun commented on base/wolfvision.hpp
> + * @author XX (2796393320@qq.com) WCJJJ (1767851382@qq.com)
作者注释统一格式为换行

2021-08-29 06:13 UTC, fqjun commented on module/roi/abstract_roi.hpp
>                       const cv::Rect& _rect) {
未对齐

2021-08-29 06:24 UTC, roboxxltd commented on module/roi/abstract_roi.hpp
>                       const cv::Rect& _rect) {
已经修复完成

2021-08-29 06:28 UTC, fqjun reviewed
允许合并

2021-08-29 06:28 UTC, merged